# Conda environment file for the project with pytorch, jupyter, transformers, and datasets

name: genaics194294

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8.18
  - pip=23.3=pyhd8ed1ab_0
  - pip:
      - absl-py==1.4.0
      - tensorflow==2.13.0
      - tensorflow-datasets==4.9.2
      - tensorflow-probability==0.21.0
      - transformers==4.35.0 
      - datasets==2.14.6
      - torch==2.1.0
      - scipy==1.10.1
      - scikit-learn==1.3.2
      - joblib
      - ipywidgets
      - widgetsnbextension
      - pandas-profiling
